feat: add refresh iframe button
element-plus/element-plus-playground pull request #240
Opened 2023-10-28 09:18 UTC by btea

Sometimes pasting the code directly will report an error. In this case, dynamically refreshing the iframe can solve the problem. Moreover, sometimes after the iframe view is resized, you want to refresh the page while maintaining the status quo. This problem can be solved by using the refresh button.

2023-10-28 12:55 UTC, btea commented
@sxzz Please review it when you are free, thank you!

2023-10-28 12:57 UTC, sxzz commented on src/components/Header.vue
> +  const iframe = document.querySelector('iframe')
Do not get iframe from the global document. Could be multiple if there's another iframe injected by browser extension.

2023-10-28 13:03 UTC, btea commented on src/components/Header.vue
> +  const iframe = document.querySelector('iframe')
Maybe we can nest a few more levels of selectors? 🤔
```js
document.querySelector('.vue-repl .iframe-container iframe')
```

2023-10-28 15:55 UTC, sxzz requested changes
`@vue/repl` exposed refresh method. We can use it directly.
https://github.com/vuejs/repl/blob/290a564c1b87c30b0c155c5c17aa9c57cc6c4bd8/src/output/Preview.vue#L271-L278

2023-10-29 13:56 UTC, btea commented
OK, thanks for the reminder.

2023-10-29 17:23 UTC, sxzz approved these changes

2023-10-29 17:24 UTC, merged